Test_Add:
  runs-on: ubuntu-latest
  needs: Compilation
  steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Test fonction add
      run: |
        cd ${{ github.workspace }}/build
        cmake ..
        make
        ./src/calculator add 10 5

Test_Subtract:
  runs-on: ubuntu-latest
  needs: Compilation
  steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Test fonction sub
      run: |
        cd ${{ github.workspace }}/build
        cmake ..
        make
        ./src/calculator sub 10 5

Test_Multiply:
  runs-on: ubuntu-latest
  needs: Compilation
  steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Test fonction mul
      run: |
        cd ${{ github.workspace }}/build
        cmake ..
        make
        ./src/calculator mul 10 5

Test_Divide:
  runs-on: ubuntu-latest
  needs: Compilation
  steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Test fonction div
      run: |
        cd ${{ github.workspace }}/build
        cmake ..
        make
        ./src/calculator div 10 5

Test_Car:
  runs-on: ubuntu-latest
  needs: Compilation
  steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Test fonction car
      run: |
        cd ${{ github.workspace }}/build
        cmake ..
        make
        ./src/calculator car 5
