Test_Add:
  runs-on: ubuntu-latest
  needs: Compilation
  steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Test fonction add
      run: |
        cd ${{ github.workspace }}/build
        cmake ..
        make
        ./src/calculator add 10 5
